### ISSUE TITLE
Expand timeline around an event.

### ISSUE THREAD

**Issue by heatheradkins** [google/timesketch#62] opened 2015-04-06 20:21 UTC
When looking at results of a Saved Search, have a button/link that pops open a new tab that shows the system's timeline with X number of records on either side of the selected entry. For example, when looking across numerous systems for 'at' jobs, if I found a new one I was interested in, I might want to see that system's timeline immediately surrounding the 'at' job.

**Comment by berggren** [comment] 2015-04-07 20:06
Thanks for the idea! Yes, this is high on the feature request list. Similar request in #60 

It would be super valuable. My thinking is that this is a kind of "zoom" feature, where you can zoom in on a event and get +-time and all events surrounding it to get context. Then zoom out again to get back to the timeline.

**Comment by berggren** [comment] 2015-04-21 14:30
This is a duplicate of #60 - Closing this one, tracking in the main issue.

**Closed by berggren** 2015-04-21 14:30 UTC
Labels: feature request
