### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by agnes-sharan** [google/timesketch#2920] opened 2023-10-01 02:43 UTC
Hi I've been following [install](https://github.com/google/timesketch/blob/master/docs/guides/admin/install.md) for the installation. However, when I am trying to do step 3, I'm confused which docker compose to use. I copied over the docker file from the docker/dev folder in the root but am getting an error that credentials are not found. I also tried to run docker up from the folder in itself. Is there some step I'm missing?

<img width="578" alt="Screenshot 2023-09-23 at 12 53 52 PM" src="https://github.com/google/timesketch/assets/30827029/5646647e-57e2-4088-a6a8-45b22b273096">

_Originally posted by @agnes-sharan in https://github.com/google/timesketch/discussions/2905_

**Comment by jkppr** [comment] 2023-10-30 14:24
I cannot reproduce this issue. I'll close the issue and help in #2905 with debugging.

**Closed by jkppr** 2023-10-30 14:24 UTC
