### ISSUE TITLE
Search timesketch.elasticsearch/ERROR not surfaced to the user

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1759] opened 2021-05-04 09:17 UTC
**Describe the bug**
Executing the below Search query is causing an ES exception that is not shown to the user resulting in an indef "Searching" in WebUi
**To Reproduce**
Search for ```(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe``` (note the unbalanced () in there.

**Expected behavior**
Show an error to the user

Raw log:

```

[2021-05-04 09:16:25,102] timesketch.elasticsearch/ERROR Unable to run search query: [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe], [query_shard_exception] Failed to parse query [(data_type:"windows\\:evtx\\:record" AND source_name:("Microsoft\\-Windows\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe]
Traceback (most recent call last):
  File "/usr/local/src/timesketch/timesketch/lib/datastores/elastic.py", line 562, in search
    _search_result = self.client.search(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/__init__.py", line 1547, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'Failed to parse query [(data_type:"windows\\\\:evtx\\\\:record" AND source_name:("Microsoft\\\\-Windows\\\\-Sysmon") AND event_identifier:("8" OR "10") AND xml_string:*powershell.exe AND xml_string:*lsass.exe]')

```

**Comment by kiddinn** [comment] 2021-05-04 09:31
not sure this is a bug ... I would rather say this is a feature request in the UI. The exception is caught and handled and it is sent to the logger... the issue here is that the UI doesn't have access to the logger, a known issue.

I'm going to reclassify this and we need to think about how we can capture logger information in the UI framewok.

**Comment by jaegeral** [comment] 2021-05-04 09:46
Well yes and now, the fact it showing "Searching" in UI while in reality it raised an exception is imho a bug

**Comment by itsmvd** [comment] 2021-05-04 09:51
This is a duplicate of https://github.com/google/timesketch/issues/1715.
I will be working on surfacing this error to the user soon.

**Closed** 2021-05-05 06:46 UTC
Labels: Feature request, UI/UX
