### ISSUE TITLE
Vagrant install fails

### ISSUE THREAD

**Issue by NetwarSystem** [google/timesketch#521] opened 2018-01-13 13:18 UTC
Vagrant install fails, this is the last little bit. The full log is in the Gist. This is on OSX with VirtualBox 5.2.4.

   default: [1/4] Resolving packages...
    default: [2/4] Fetching packages...
    default: info fsevents@1.1.2: The platform "linux" is incompatible with this module.
    default: info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
    default: [3/4] Linking dependencies...
    default: warning "@angular/compiler-cli > tsickle@0.23.6" has incorrect peer dependency "typescript@2.3.4".
    default: warning " > codelyzer@3.2.0" has incorrect peer dependency "@angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0".
    default: warning " > codelyzer@3.2.0" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
    default: warning " > karma-jasmine@1.1.0" has unmet peer dependency "jasmine-core@*".
    default: error Could not write file "/usr/local/src/timesketch/yarn-error.log": "EACCES: permission denied, open '/usr/local/src/timesketch/yarn-error.log'"
    default: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    default: error An unexpected error occurred: "EACCES: permission denied, mkdir '/usr/local/src/timesketch/node_modules'".

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

https://gist.github.com/NetwarSystem/f83742e2334af8f9abebb616856ea98e

**Comment by berggren** [comment] 2018-01-13 16:32
Thanks for the report! I will try to reproduce this and fix asap.

**Comment by adamjnichols** [comment] 2018-01-13 17:16
Do you have overly restrictive permissions on /Users/litwin/src/timesketch?

**Comment by NetwarSystem** [comment] 2018-01-13 19:48
drwxr-xr-x   5 litwin  staff   160 Jan 13 05:01 .
drwxr-xr-x+ 67 litwin  staff  2144 Jan 13 05:24 ..
drwxr-xr-x  17 litwin  staff   544 Dec 30 14:25 lighthouse
drwxr-xr-x  31 litwin  staff   992 Jan 13 05:01 timesketch
drwxr-xr-x  93 litwin  staff  2976 Dec 15 14:49 uemacs

**Comment by NetwarSystem** [comment] 2018-01-13 20:17
But I think that is a vagrant system perms issue, not the host OS. I don't see any reason a process couldn't write stuff here ... unless yarn has its own user or something? Or does yarn.lock hanging around keep the process from completing?

vagrant@timesketch-dev:/usr/local/src$ ls -la
total 8
drwxr-xr-x  3 root    root    4096 Jan 13 13:05 .
drwxr-xr-x 10 root    root    4096 Jan 12 14:25 ..
drwxr-xr-x  1 vagrant vagrant  992 Jan 13 13:01 timesketch

vagrant@timesketch-dev:/usr/local/src/timesketch$ ls -l
total 260
drwxr-xr-x 1 vagrant vagrant     96 Jan 13 13:01 api_client
-rw-r--r-- 1 vagrant vagrant    314 Jan 13 13:01 AUTHORS
drwxr-xr-x 1 vagrant vagrant    224 Jan 13 13:01 contrib
-rw-r--r-- 1 vagrant vagrant   4223 Jan 13 13:01 CONTRIBUTING.md
drwxr-xr-x 1 vagrant vagrant    192 Jan 13 13:01 docker
drwxr-xr-x 1 vagrant vagrant    288 Jan 13 13:01 docs
-rw-r--r-- 1 vagrant vagrant   1085 Jan 13 13:01 karma.conf.js
-rw-r--r-- 1 vagrant vagrant   1593 Jan 13 13:01 karma-coverage.conf.js
-rw-r--r-- 1 vagrant vagrant  11358 Jan 13 13:01 LICENSE
-rw-r--r-- 1 vagrant vagrant    152 Jan 13 13:01 MANIFEST.in
-rw-r--r-- 1 vagrant vagrant   2743 Jan 13 13:01 package.json
-rw-r--r-- 1 vagrant vagrant   1615 Jan 13 13:01 README.md
-rw-r--r-- 1 vagrant vagrant    873 Jan 13 13:01 requirements.in
-rw-r--r-- 1 vagrant vagrant   2217 Jan 13 13:01 requirements.txt
-rwxr-xr-x 1 vagrant vagrant   3434 Jan 13 13:01 run_tests.py
-rw-r--r-- 1 vagrant vagrant   3175 Jan 13 13:01 setup.py
drwxr-xr-x 1 vagrant vagrant    384 Jan 13 13:01 timesketch
-rw-r--r-- 1 vagrant vagrant   3640 Jan 13 13:01 timesketch.conf
-rw-r--r-- 1 vagrant vagrant    402 Jan 13 13:01 tsconfig.json
-rw-r--r-- 1 vagrant vagrant  19892 Jan 13 13:01 tsctl
-rw-r--r-- 1 vagrant vagrant   2879 Jan 13 13:01 tslint.json
drwxr-xr-x 1 vagrant vagrant    320 Jan 13 13:03 vagrant
-rw-r--r-- 1 vagrant vagrant   1782 Jan 13 13:01 webpack.config.js
-rw-r--r-- 1 vagrant vagrant 166110 Jan 13 13:01 yarn.lock

**Comment by NetwarSystem** [comment] 2018-01-13 20:42
Had a go at logging in to vagrant machine and trying to manually finish install. There was a little issue with python setup.py install, correct this manually and stuff kinda runs.

Searching for pycypher==0.5.9
Reading https://pypi.python.org/simple/pycypher/
No local packages or working download links found for pycypher==0.5.9
error: Could not find suitable distribution for Requirement.parse('pycypher==0.5.9')
root@timesketch-dev:/usr/local/src/timesketch# pip install pycypher
The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/vagrant/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pycypher
  Downloading pycypher-0.5.9-52-cp27-cp27mu-manylinux1_x86_64.whl (610kB)
    100% |████████████████████████████████| 614kB 2.0MB/s 
Installing collected packages: pycypher
Successfully installed pycypher-0.5.9

This leaves timesketch.conf in the install directory, system complains it's not in /etc/ - and no database config has been done. Tried switching to sqlite, that's not a solution. So finished the setup per manual install, creating user for postgres, etc. This gets me a running timesketch instance on http://localhost:5000, but ...

python tsctl runserver -h 0.0.0.0 -p 5000
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 284-810-970
10.0.2.2 - - [13/Jan/2018 20:35:20] "POST /login/?next=%2F HTTP/1.1" 400 -
10.0.2.2 - - [13/Jan/2018 20:35:23] "POST /login/?next=%2F HTTP/1.1" 400 -
10.0.2.2 - - [13/Jan/2018 20:35:26] "GET / HTTP/1.1" 302 -
10.0.2.2 - - [13/Jan/2018 20:35:26] "GET /login/?next=%2F HTTP/1.1" 200 -
10.0.2.2 - - [13/Jan/2018 20:35:26] "GET /static/dist/bundle.css HTTP/1.1" 404 -
10.0.2.2 - - [13/Jan/2018 20:35:32] "POST /login/?next=%2F HTTP/1.1" 302 -
/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.1.13-py2.7-linux-x86_64.egg/sqlalchemy/sql/default_comparator.py:161: SAWarning: The IN-predicate on "sketch_accesscontrolentry.group_id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
10.0.2.2 - - [13/Jan/2018 20:35:32] "GET / HTTP/1.1" 200 -
10.0.2.2 - - [13/Jan/2018 20:35:32] "GET /static/dist/bundle.css HTTP/1.1" 404 -
10.0.2.2 - - [13/Jan/2018 20:35:32] "GET /static/dist/bundle.js HTTP/1.1" 404 -
10.0.2.2 - - [13/Jan/2018 20:35:32] "GET /static/img/favicon.ico HTTP/1.1" 200 -

This instance has the same problem as the manual install does after updating timesketch from github.

https://imgur.com/a/8LpZN

My workaround-fu is not strong enough to fix this ...

**Comment by adamjnichols** [comment] 2018-01-13 20:56
The directory in the error -- the one i asked about before -- is a direct mount from your host system.  See line 24 of the Vagrantfile.  They share permissions, and changes on one will be reflected on the other in real time, hence my question.  There isn't a Vagrant "system", per se; only the VM created with the parameters specified by Vagrant.

The lockfile will have nothing to do with this issue.

I'm not able to reproduce this issue running VB 5.1.30 or VB 5.2.4 with Vagrant 2.0.1 on OS X High Sierra.  Your workaround foo is pretty strong, but Timesketch is fairly complex with multiple distributed and code-based dependencies, which is why the Vagrant/Docker options exist to streamline the install.

In your long listing on the host, all files are owned by vagrant:vagrant, but should be owned by ubuntu:ubuntu.  There should not even be a vagrant user on the system once completed, and nothing in the timesketch vagrantfile that would create one.  Do you happen to have a nonstandard config in ~/.vagrant.d/Vagrantfile on the host box?

**Comment by NetwarSystem** [comment] 2018-01-13 21:25
I played with Vagrant a bit a few years ago, not something I use regularly. VirtualBox is a daily staple.

This is the Vagrant I used for install

-rw-r--r--@ 1 litwin  staff  73365198 Jan 13 04:45 vagrant_2.0.1_x86_64.dmg

My long term objective is to 'colocate' Timesketch with Wazuh for event analysis, and then I've got some other stuff of my own where it would be useful. It's gotta run on Ubuntu (or Debian or CentOS) and in at least one instance it'll be running on a three host Elasticsearch 6.1.1 cluster. I'm only touching the Vagrant stuff because I want to play with the system a bit so I can be sure it's a solution for the problems at hand - someone else I work with asked for this.

Some of the target environment is dedicated hardware, but there is a Xen Orchestra cloud, and I think there will be some VMware ESXi coming this quarter.

**Comment by adamjnichols** [comment] 2018-01-13 22:18
Think I found your issue... the 20180105 Vagrant ubuntu/xenial specified ubuntu as the ssh user; the 20180112 removes that config.

In timesketch/vagrant/bootstrap.sh on line 14, can you change the RUN_AS_USER to be "vagrant" and try again?

**Comment by adamjnichols** [comment] 2018-01-13 22:20
Think I found your issue... the 20180105 Vagrant ubuntu/xenial specified ubuntu as the ssh user; the 20180112 removes that config.  Give me a bit.

**Comment by NetwarSystem** [comment] 2018-01-13 22:30
de novo Vagrant & Timesketch - wiped Vagrant, gave the Timesketch git repository it's own directory, chmod -R 755.

https://gist.github.com/NetwarSystem/8dacaace99058eadf18cf7e14879ada1

Just in case you need it ... glad to hear you might have a smoking gun. I'm gonna go beat up on Wazuh while you're doing that ...

**Comment by adamjnichols** [comment] 2018-01-13 23:39
if you are able to test with the xenial 20180105 version, you should be able to run without issue.  Will take me a bit to solve for this...

**Comment by NetwarSystem** [comment] 2018-01-14 00:13
How do I pull that? I'm poking around in web interface, don't see that branch.

**Comment by adamjnichols** [comment] 2018-01-15 04:20
Sorry this took a bit.  If you clone the ajn-vagrant-fixes branch, you should be good to go.  Hopefully berggren@ will be around to merge #523 soon. :)

As to your last question, you can install multiple versions of a vagrant box, like so:

```
vagrant box add ubuntu/xenial64 --box_version=20180105.0.0
```

**Comment by berggren** [comment] 2018-01-15 07:42
The fix has been merged. Thanks Adam for fixing this!

**Comment by berggren** [comment] 2018-01-15 07:42
I'm closing this one, please re-open if the problem persists.

**Closed by berggren** 2018-01-15 07:42 UTC

**Comment by NetwarSystem** [comment] 2018-01-15 08:01
I did this:

vagrant box add ubuntu/xenial64 --box_version=20180105.0.0

And then a vagrant up ... dying with same error as before:


    default: Preparing to unpack .../nodejs_8.9.4-1nodesource1_amd64.deb ...
    default: Unpacking nodejs (8.9.4-1nodesource1) ...
    default: Selecting previously unselected package yarn.
    default: Preparing to unpack .../archives/yarn_1.3.2-1_all.deb ...
    default: Unpacking yarn (1.3.2-1) ...
    default: Processing triggers for man-db (2.7.5-1) ...
    default: Setting up nodejs (8.9.4-1nodesource1) ...
    default: Setting up yarn (1.3.2-1) ...
    default: yarn install v1.3.2
    default: [1/4] Resolving packages...
    default: [2/4] Fetching packages...
    default: info fsevents@1.1.2: The platform "linux" is incompatible with this module.
    default: info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
    default: [3/4] Linking dependencies...
    default: warning "@angular/compiler-cli > tsickle@0.23.6" has incorrect peer dependency "typescript@2.3.4".
    default: warning " > codelyzer@3.2.0" has incorrect peer dependency "@angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0".
    default: warning " > codelyzer@3.2.0" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
    default: warning " > karma-jasmine@1.1.0" has unmet peer dependency "jasmine-core@*".
    default: error Could not write file "/usr/local/src/timesketch/yarn-error.log": "EACCES: permission denied, open '/usr/local/src/timesketch/yarn-error.log'"
    default: error An unexpected error occurred: "EACCES: permission denied, mkdir '/usr/local/src/timesketch/node_modules'".
    default: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by adamjnichols** [comment] 2018-01-15 16:49
Sorry, let me be more clear about what I'm explaining...

The issue you've uncovered (thanks, btw) is due to the usernames in play during install.  Vagrant uses versioned "boxes" when a system is created, in our case, ubuntu/xenial64.  These are released every week or so, as you can see [here](https://app.vagrantup.com/ubuntu/boxes/xenial64).  If you examine ~/.vagrant.d/boxes/, you can see the major types (in our case, it's ubuntu-VAGRANTSLASH-xenial64), and within those types, the individual, dated versions.  Within those folders, you'll find a Vagrantfile with a base config for building those systems.

Beginning with version 20180109.0.0, this system removed the following stanza from the Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.base_mac = "0206A9F472F7"
  config.ssh.username = "ubuntu"
  config.ssh.password = "9d98e40e98ec6b9179f13044"
```

Because our previous bootstrap.sh was executing a number of commands as the user 'ubuntu', this was fine.  One might argue that this *should* be durable based on the prolific use of the ubuntu username across most Canonical projects.  However, when this config was removed from the box's Vagrantfile, it defaults to the user 'vagrant', which means that we encounter a number of issues attempting to make files and do install work as the ubuntu user within directories owned and permissioned for the 'vagrant' user.  This is the reason you see the errors that you do.

Therefore, you have two options for making this work:

- Create a new clone of timesketch from master, and use the most recent version of the ubuntu/xenial64 vagrant box (which is currently 20180112.0.0).
- You can keep the older copy of timesketch (prior to merge #523), and ensure you are using a version of the ubuntu/xenial64 vagrant box prior to 20180109.0.0
