### ISSUE TITLE
[UI] It isn't clear which "tab" is selected

### ISSUE THREAD

**Issue by binglot** [google/timesketch#1979] opened 2021-10-13 23:06 UTC
**Describe the bug**
When you click on a tab like Explore or Intelligence, it's not easily distinguishable that you're in this particular tab as compared to all other tabs. We used to have an underscore as shown in the screenshot below but now it's just a "darker" text, which is very subtle in both light and dark modes.

**Expected behavior**
We used to have an underscore for the tab that was active, that's one possible solution.

**Screenshots**
Currently (light mode):

![image (1)](https://user-images.githubusercontent.com/1036124/137224503-2c939f6e-7f14-422b-975e-6ce3b355bf3e.png)

Currently (dark mode):

![image (2)](https://user-images.githubusercontent.com/1036124/137224561-d8481c83-9ba3-4248-a1c2-b26b26a75811.png)

In the past:

![image (3)](https://user-images.githubusercontent.com/1036124/137224593-35df2e86-b6f5-49fa-9307-d43e3bb4ffaf.png)

**Comment by kitsiosvas** [comment] 2022-01-26 22:05
Hello, I am interested working on this feature if possible. The underscore option seems easily distinguishable and it is also used widely, so keeping up with known standards is a plus. I will search for other possible solutions as well. 
Also, how does the underscore look with the dark mode enabled? Does it remain visible?
Thank you.

**Comment by binglot** [comment] 2022-01-27 03:36
Hey @kitsiosvas , you can set up Timesketch on your development machine and test it out yourself. I don't think the behaviour has been changed so it's most likely the same as in the screenshots attached. Let me know if you need help with anything. Thanks!

**Comment by kitsiosvas** [comment] 2022-01-27 12:24
@binglot Thank you for your response, could you be so kind and pointing out the location where the feature is implemented.
I will start working on it immediately.

**Comment by binglot** [comment] 2022-01-28 00:36
The source code for the front-end is in `https://github.com/google/timesketch/tree/master/timesketch/frontend/src`. You'll need to find the code or CSS that's responsible for "highlighting" of selected tabs.

**Comment by jaegeral** [comment] 2022-08-22 20:00
@binglot do you think the problem is still valid with the new UI or could we close this one out?

**Comment by binglot** [comment] 2022-08-24 15:51
@jaegeral - with the new UI coming out and since I haven't seen the old UI in over 2 months, I can't judge if this is still the case. If you navigate to Timesketch and toggle between the default and darkmode, you should be able to tell if it's visible enough to tell which tab you're currently in.

**Comment by jaegeral** [comment] 2022-12-02 21:05
yeah this will no longer be an issue in the new UI, so I think fair to close this one.

**Closed by jaegeral** 2022-12-02 21:05 UTC
Labels: Bug, UI/UX, Small effort
