### ISSUE TITLE
[browser_search] Error decoding event.

### ISSUE THREAD

**Issue by aguilajesus** [google/timesketch#774] opened 2019-01-09 14:41 UTC
[ERROR/ForkPoolWorker-1] Task timesketch.lib.tasks.run_sketch_analyzer[x] raised unexpected: UnicodeEncodeError('ascii
', u'It\xe2\x80\x99s a test.', 2, 5, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/local/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/local/lib/python2.7/site-packages/timesketch/__init__.py", line 159, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/local/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/local/lib/python2.7/site-packages/timesketch/lib/tasks.py", line 256, in run_sketch_analyzer
    result = analyzer.run_wrapper()
  File "/local/lib/python2.7/site-packages/timesketch/lib/analyzers/interface.py", line 30, in wrapper
    func_return = func(self, *args, **kwargs)
  File "/local/lib/python2.7/site-packages/timesketch/lib/analyzers/interface.py", line 337, in run_wrapper
    result = self.run()
  File "/local/lib/python2.7/site-packages/timesketch/lib/analyzers/browser_search.py", line 206, in run
    event.add_attributes({'search_string': search_query})
  File "/local/lib/python2.7/site-packages/timesketch/lib/analyzers/interface.py", line 85, in add_attributes
    self._update(attributes)
  File "/local/lib/python2.7/site-packages/timesketch/lib/analyzers/interface.py", line 77, in _update
    event=event)
  File "/local/lib/python2.7/site-packages/timesketch/lib/datastores/elastic.py", line 518, in import_event
    for k, v in event.items()
  File "/local/lib/python2.7/site-packages/timesketch/lib/datastores/elastic.py", line 518, in <dictcomp>
    for k, v in event.items()
  File "/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-4: ordinal not in range(128)

**Comment by kiddinn** [comment] 2019-01-14 20:20
Is this still an issue?

**Comment by kiddinn** [comment] 2019-01-25 17:56
Yes, this is still an issue, confirmed it.

**Comment by joachimmetz** [comment] 2020-06-17 14:29
@kiddinn @aguilajesus is this still an issue since TS is on Python 3 now?

**Comment by berggren** [comment] 2020-06-26 11:34
This should have been fixed now. @kiddinn can you confirm and close this out?

**Comment by kiddinn** [comment] 2020-07-07 09:56
this should be fixed with the move to py3, and several changes to teh code.

I will close this for now, if this is still an issue, then a new stacktrace is needed since the code has been moved to py3 since this occurred.

**Closed by kiddinn** 2020-07-07 09:56 UTC
Labels: Bug, Issue health
