### ISSUE TITLE
Context Query not working

### ISSUE THREAD

**Issue by n3x77** [google/timesketch#241] opened 2016-10-25 11:10 UTC
Hi, 

after installing the current version of timesketch with pip it seems that the context query option does not work any more. After clicking on the context query icon of a timeline entry nothing happens.

Timesketch was installed yesterday via pip. Running on postgresql 9.3,  JVM: 1.7.0_111 ES: 2.4.1 and Ubuntu 14.04 LTS. 

Bye
Sven

**Comment by berggren** [comment] 2016-10-27 15:40
Hey,

This is a temporary feature regression. I needed to disable it due to some
refactoring work on the angular front-end code. It will be re-enabled as
soon as possible.

Sorry for the inconvenience.

/jbn

**Comment by n3x77** [comment] 2016-10-28 08:44
Hey, 

thanks for the response!
For us it is one of the best features of timesketch, so it would be great if it could be re-enabled soon :-)

Bye,
Sven

**Comment by berggren** [comment] 2016-11-04 09:42
Hey @n3x77 - Context queries are back! HEAD is updated so this will be part of the next release.

**Closed by berggren** 2016-11-04 09:42 UTC
Labels: bug, enhancement, refactor

**Comment by n3x77** [comment] 2016-11-07 10:42
@berggren Thx! Great to hear!
