### ISSUE TITLE
Internal server error + ApiHTTPError

### ISSUE THREAD

**Issue by adrastee** [google/timesketch#579] opened 2018-04-17 09:31 UTC
Hi,
I've installated Timesketch yesterday from scratch on Ubuntu, following the guide.
I am trying to send a plaso file (45 gb) to this server (in my LAN).
It fails, on the GUI I have "Internal Server Error" and on the server I have the error "ApiHTTPError" here is the trace: http://oi67.tinypic.com/21ot4ph.jpg

Is the file too big ? If yes, how can I send it ?

Thank you!

**Comment by berggren** [comment] 2018-04-17 14:16
Hi, thanks for your report. I can't see the trace you linked to, but I think that this is due to the large file upload timing out. That is a huge Plaso file :)

You can copy the file to the server and run:
```$ psort.py -o timesketch filename.plaso```

**Comment by adamjnichols** [comment] 2018-04-17 16:54
Hi there -- have you enabled upload support in /etc/timesketch.conf?  Looks like you're getting the BAD_REQUEST error, which we most typically see related to this issue.  Might be worth checking in case you need to upload smaller files in the future, but as Johan mentioned, files of that size aren't really intended for HTTP upload. :)

**Comment by adrastee** [comment] 2018-04-26 08:40
Hi,
Sorry, the plaso sqlite file was 40 MB (and not GB).
Here are my unsuccessful tries:

**Try with plaso.sqlite (from plaso version 20180127)  and upload this sqlite file to webapp**
-> internal error / ApiHTTPError
Why ?

**Try with plaso.csv - using psort -o l2tcsv -  and upload this csv file to webapp**
-> upload is OK, but "0.0 Events" recorded in Timesketch, while psort gives me  23701 events.
Why ?

**Try with plaso.json- using psort -o json and upload this json file to webapp**
-> internal error / ApiHTTPError

**Then I read from Wiki:**
>tsctl csv2ts --name my_timeline --file timeline.csv
>tsctl json2ts --name my_timeline --file timeline.json

Both commands gave me this error:
```
tsctl csv2ts --name testCSV  --file /home/xxx/plaso.csv
Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 430, in <module>
    shell_manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/bin/tsctl", line 353, in run
    es.create_index(index_name=index_name, doc_type=event_type)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/datastores/elastic.py", line 377, in create_index
    if not self.client.indices.exists(index_name):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 213, in exists
    params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 175, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fa2598f0a50>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fa2598f0a50>: Failed to establish a new connection: [Errno 111] Connection refused)
```

Then I tried your command @berggren 
> You can copy the file to the server and run:
> $ psort.py -o timesketch filename.plaso

`python /usr/lib/python2.7/dist-packages/plaso/cli/psort_tool.py -o timesketch  /home/xxx/plaso.sqlite -w /home/xxx/plaso.ts`
Gives no output - no file created.

So i'm completely stuck !

Thank you for your help.

**Comment by adamjnichols** [comment] 2018-04-26 15:36
Ok, so much to unpack here.  First things first:

1) Can you provide the server-side output here?  Hard to say why without more info.
2) There is a bit of a delay between the time that the file is uploaded, and when it's available.  This is denoted by the spinning indicator adjacent to the timeline name in the sketch overview tab.  Once the indexing is complete and the timeline is available, you should see a timeline color instead of an indicator.  Is that present?  If not, are there errors on the server-side?
3) See #1
4) From this error, it appears that you do not have an instance of Elasticsearch running, or that the URL you've provided in /etc/timesketch.conf is incorrect.  Could you try to correct that and run again?
5) If you have issue with ES, probably nothing you do is going to work the way we expect.  Also, you'll note that your command is different than the one provided by berggren, he has omitted the "-w" flag.  When providing timesketch as a plaso output option, it will write directly into timesketch and not a file.  However, as before, if there is no good conn to ES, this will fail accordingly.

You mention that you're trying to install from scratch -- may i ask why?  Timesketch is a fairly complex project that requires a number of distributed components to function as expected, so for most use cases we recommend either the Docker or Vagrant install options, as they are self-contained and handle all of those dependencies for you.  If you are working at a larger scale or have requirements those options can't meet, we're happy to make recommendations, but the presence of a postgres instance, an elasticsearch instance, celery worker instance(s), and other components will be necessary for that to run as you expect.

**Comment by adrastee** [comment] 2018-05-03 11:15
Thanks for your help @adamchainz.
I am following your advice and go for Docker instead.
For the record, here are my answer:
1.  server side error is shown here: http://oi67.tinypic.com/21ot4ph.jpg
2. I am sure the indexing was completed as no indicator was present, and I saw the timeline color.
3.  Same 1.
4 and 5. I will try Docker instead.

**Comment by adamchainz** [comment] 2018-05-03 11:16
you @'d the wrong adam

**Comment by adamjnichols** [comment] 2018-05-03 15:09
So, the error that you posted isn't an error, per se; it's the stacktrace that provides me a bit more info, but the bit you highlighted is our code designed to return an error to you.  That specific bit occurs when there is an issue with the file that you've uploaded, or attempted to upload.  What is the extension of that file?  Are you able to provide the response received by the browser?

Also, I've seen your other issue post related to running docker.  I'm sorry to see that you keep running into roadblock after roadblock, but there is an known issue with long pathing in virtual environments on Windows 10 that we're not able to overcome.  Please see issue #547 for more info and pointers to a Vagrant bug that describes the issue in more detail.  In general, your best bet is to run Timesketch in a linux environment regardless if installing from scratch or using containerized deployment.

My email is listed in my profile -- please feel free to ping me offline as you're working through these issue.  Happy to help you there if I can.

**Comment by adrastee** [comment] 2018-06-08 13:08
Thanks a lot.
I finally manage to get docker and timesketch intalled :) Will try to upload things inside soon.

**Comment by adamjnichols** [comment] 2018-06-19 16:12
Hi there -- how are you attempting this upload?  Can you please provide the command and the container you're running from?

**Comment by adrastee** [comment] 2018-06-20 14:45
Hi,
"how are you attempting this upload?" by clicking on the button "import timeline" in the main UI, I select the CSV file, and then "upload" button.
Command line of the container is ./docker-entrypoint.sh timesketch

**Comment by adamjnichols** [comment] 2018-06-26 17:34
The Docker environment should not be started using the entrypoint.  We rely on docker-compose for Timesketch.  Please reference the Docker documentation for more info:

https://github.com/google/timesketch/tree/master/docker

**Comment by adrastee** [comment] 2018-07-03 15:12
I started with "docker-compose up" command, and tried to upload the example csv, and I got:
"Internal Server Error" in the web browser
and in the logs:

```
timesketch_1     | [2018-07-03 15:10:28,801] ERROR in app: Exception on /api/v1/upload/ [POST]
timesketch_1     | Traceback (most recent call last):
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
timesketch_1     |     rv = self.dispatch_request()
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
timesketch_1     |     return self.view_functions[rule.endpoint](**req.view_args)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
timesketch_1     |     resp = resource(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
timesketch_1     |     return self.dispatch_request(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
timesketch_1     |     resp = meth(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
timesketch_1     |     return func(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 1083, in post
timesketch_1     |     status_code=HTTP_STATUS_CODE_BAD_REQUEST)
timesketch_1     | ApiHTTPError
```

What is wrong ?

**Comment by rayschippers** [comment] 2018-12-08 08:55
Getting the exact same error, was this ever resolved?
```
12/8/2018 4:51:57 PM[2018-12-08 08:51:57,178] ERROR in app: Exception on /api/v1/upload/ [POST]
12/8/2018 4:51:57 PMTraceback (most recent call last):
12/8/2018 4:51:57 PM  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
12/8/2018 4:51:57 PM    rv = self.dispatch_request()
12/8/2018 4:51:57 PM  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
12/8/2018 4:51:57 PM    return self.view_functions[rule.endpoint](**req.view_args)
12/8/2018 4:51:57 PM  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
12/8/2018 4:51:57 PM    resp = resource(*args, **kwargs)
12/8/2018 4:51:57 PM  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 88, in view
12/8/2018 4:51:57 PM    return self.dispatch_request(*args, **kwargs)
12/8/2018 4:51:57 PM  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
12/8/2018 4:51:57 PM    resp = meth(*args, **kwargs)
12/8/2018 4:51:57 PM  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
12/8/2018 4:51:57 PM    return func(*args, **kwargs)
12/8/2018 4:51:57 PM  File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 1068, in post
12/8/2018 4:51:57 PM    status_code=HTTP_STATUS_CODE_BAD_REQUEST)
12/8/2018 4:51:57 PMApiHTTPError
```

**Comment by rayschippers** [comment] 2018-12-08 09:11
So a further investigation if I upload a JSON I get this error, uploading a plaso file it works fine.

**Comment by kiddinn** [comment] 2019-10-21 20:50
is this resolved by now?

**Comment by berggren** [comment] 2020-01-08 09:31
Closing this as the last response was over a year ago. Please reopen if the issue is still there.

**Closed by berggren** 2020-01-08 09:31 UTC
Labels: Support
