### ISSUE TITLE
Internal server error ReadTimeoutError: HTTPConnectionPool(host='elasticsearch', port=9200): Read timed out. (read timeout=10)

### ISSUE THREAD

**Issue by berggren** [google/timesketch#1839] opened 2021-06-17 15:34 UTC
### Discussed in https://github.com/google/timesketch/discussions/1828

<div type='discussions-op-text'>

<sup>Originally posted by **SkyBlue-B** June 15, 2021</sup>
Hi, 
We are experiencing issues with web ui access, internal server error. Is there a solution to this?

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</div>

**Comment by berggren** [comment] 2021-06-17 15:35
@SkyBlue-B Please add the server error logs here so we can see what is going on.

**Comment by fancybear-dev** [comment] 2021-07-01 08:07
I've been having internal server error's as well. Have not been able to fix them yet. It's due to the built-in timeout of flask? of 10 seconds. It queries elasticsearch and because of the amount of data - it takes longer than 10 seconds and timesketch just says error.

**Comment by fancybear-dev** [comment] 2021-07-01 08:08
You can verify this in the opt/timesketch/logs/wsgi log file.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 241, in perform_request
    response = self.pool.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='elasticsearch', port=9200): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/sketch.py", line 385, in get
    count_agg = self.datastore.client.search(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/__init__.py", line 1547, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 253, in perform_request
    raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='elasticsearch', port=9200): Read timed out. (read timeout=10))`

**Comment by fancybear-dev** [comment] 2021-07-01 08:18
https://github.com/google/timesketch/pull/1849

**Comment by jaegeral** [comment] 2021-07-01 08:45
Did you run any analyzer before by any chance?

**Comment by fancybear-dev** [comment] 2021-07-01 08:54
On this system yes, but had the same error on a much more powerful server that hadn't ran any analyzers - which had the same issue in the end.

One thing to note here is, that we're importing around 110 plaso files into timesketch/elastic and the total amount of events is around 4 billion. The elastic cluster isn't fast enough to process the request in time. Have been looking in how we can improve the performance of the elastic cluster - but haven't found any solutions yet on that.

**Comment by jaegeral** [comment] 2021-07-01 09:00
Ok thx, because I had the same issue when running analyzers that create a lot of search queries and then elastic needs some time to catch up.

**Comment by jaegeral** [comment] 2022-08-22 20:11
I think we have fixed that with https://github.com/google/timesketch/pull/1958. I am going to close this issue. Feel free to comment on it or create a new one if the problem re-appears.

If it comes back, please consider using: https://timesketch.org/guides/admin/troubleshooting/ and provide logs and description on what was ran last, how much data has the sketch that caused it, how much CPU / Disk / RAM has the machine as this has an impact of those type of timeout errors.

Thx

**Closed by jaegeral** 2022-08-22 20:11 UTC
Labels: Support
