### ISSUE TITLE
Display timeline index name in the UI

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#189] opened 2016-07-13 17:27 UTC
Note: This isn't a duplicate for the same functionality as enabling/disabling Timelines to query within Explore > Filters.

In this scenario,
- I have multiple timelines attached to a sketch and they're all enabled. These timelines include network/filesystem data for X number of systems.
- I have previously tagged events across all selected timelines that involved a term (e.g. queried for an IP Address across all of them)
- I want to create a view that contains all of starred events for said term + all starred events in a specific timeline. (e.g. - The view should contain all starred events containing the compromised IP address + all starred events for the timeline that's specific to the file system timeline associated with the compromised host to track the attackers activity both laterally and on the compromised system)

Two options come to mind:
1. ability to create a new view by combining multiple views
2. the ability to add a query parameter to the Explorer search box that allows one to also filter on a specific timeline name or timeline id.

e.g. - `__ts_star AND (*10.0.0.1* OR timeline_name:compromised_host_timeline_name)`

IMO I think option 2 is the better route. Please let me know if this use case makes sense.

**Comment by berggren** [comment] 2016-08-20 12:19
Interesting. There are multiple ways of doing this, and I actually thinks that #2 is already possible using the _index attribute. I need to test this though.

Multiple filters would be awesome.

**Comment by berggren** [comment] 2017-02-25 10:40
Yeah, so this is possible with the _index attribute. The problem is that the index name is just a uuid and is not very userfriendly to handle. I have to think about this a bit more, but will close this out and start another issue with the UI part of it.

Ex:
_all:"foobar" AND _index:"4567234522aa42ffa142240c27b85123"

**Comment by berggren** [comment] 2017-02-25 10:42
Never mind, I will use this issue to track the UI changes :)

**Closed** 2017-08-16 13:52 UTC
Labels: feature-req
