### ISSUE TITLE
Graph queries all come back blank

### ISSUE THREAD

**Issue by shortstack** [google/timesketch#965] opened 2019-08-20 20:29 UTC
Running Timesketch in Docker, `aorlikoski/skadi_timesketch:20190326`, zero issues with anything, except Graph.

Graph feature is enabled in timesketch.conf. 

We imported about 90 million events and a dozen timelines. We tried running Graph queries, and it consistently comes back blank. No errors, docker logs show 200's and lots of `POST /api/v1/sketches/1/event/annotate/ => generated 169 bytes in 44 msecs (HTTP/1.1 201) 3 headers in 91 bytes (1 switches on core 0)`

But graphs are consistently blank.

The only errors I see are in the developer console in the browser.

Any help is appreciated. I sincerely hope it's something dumb that I did on my end. Thank you.

<img width="785" alt="Screenshot 2019-08-20 16 27 56" src="https://user-images.githubusercontent.com/1244979/63381823-78f6d180-c367-11e9-9160-33c95cf1b5d5.png">

<img width="1467" alt="Screenshot 2019-08-20 16 24 21" src="https://user-images.githubusercontent.com/1244979/63381764-5c5a9980-c367-11e9-95f4-a3d49aab9906.png">

**Comment by kiddinn** [comment] 2019-10-19 09:56
yes, the graphing needs to be revived, this is a KI

**Comment by shortstack** [comment] 2019-10-26 18:29
thank you!

**Comment by GalacticMaster** [comment] 2020-01-28 05:37
Facing same issue. when checked Neo4j logs it shows not starting. Something related to lock files.
Caused by: org.neo4j.kernel.StoreLockException: Unable to obtain lock on store lock file: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)

**Comment by berggren** [comment] 2020-06-26 12:06
Closing this one out as the graph feature is being rewritten and this will be obsolete. @shortstack let me know if you wanna be an early tester of the new implementation :)

**Closed by berggren** 2020-06-26 12:06 UTC
Labels: Bug

**Comment by shortstack** [comment] 2020-06-26 12:10
thank you!
