### ISSUE TITLE
Error when adding intelligence: Value needs to be a string

### ISSUE THREAD

**Issue by cudeso** [google/timesketch#2031] opened 2021-11-14 16:11 UTC
**Describe the bug**
When adding a value ('other', 'hostname') as intelligence I get the error message "Internal Server Error" in the Timesketch UI.

**To Reproduce**
1. Open sketch, select timeline
2. Select a string, fe 'MYCP'
3. Select 'other', 'Add' (the error occurs for every type of intelligence)

**Expected behavior**
Adding intelligence without an error

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Version: Latest Docker versions (installed according to https://github.com/google/timesketch/blob/master/docs/guides/admin/install.md )

**Additional context**

The output from /**var/log/timesketch/wsgi_error.log** in the Docker container **us-docker.pkg.dev/osdfir-registry/timesketch/timesketch:latest** returned this error
```
[2021-11-13 20:41:36,070] timesketch.app/ERROR Exception on /api/v1/sketches/1/attribute/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/attribute.py", line 136, in post
    value_strings = [ontology_lib.OntologyManager.encode_value(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/attribute.py", line 136, in <listcomp>
    value_strings = [ontology_lib.OntologyManager.encode_value(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/ontology.py", line 186, in encode_value
    return cls._types[type_string].encode(value)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/ontology.py", line 61, in encode
    raise ValueError('Value needs to be a string.')
ValueError: Value needs to be a string.
```

**Comment by tomchop** [comment] 2021-11-15 10:59
Thanks for filing @cudeso! Can you tell us a bit more about what your setup looks like? I'm interested in what your /etc/timesketch/ontology.yaml file **in the container** looks like.

Can you get a shell in the conainer:

```
~/timesketch/docker/dev$ sudo docker-compose exec timesketch /bin/bash
```

and then

```
root@65a8aacfcdbd:/# cat /etc/timesketch/ontology.yaml
# Define the ontology that is available for Timesketch.
# An ontology needs to define the name, which is what will
# be used to identify the ontology.
# + cast_as is used to define how the value should be
#       interpreted in code.
# + description is a short text describing the ontology.

text:
        cast_as: str
        description: "Free form text."

int:
        cast_as: int
        description: "Integer"

url.safe:
        cast_as: str
        description: "Safe URL that can be visited."

url.bad:
        cast_as: str
        description: "URL related to a sketch, can morph into a search."

domain:
        cast_as: str
        description: "Domain related to a sketch, can morp into a search."

float:
        cast_as: float
        description: "Float."

bool:
        cast_as: bool
        description: "Boolean, True or False values."

intelligence:
        cast_as: dict
        description: "Set of key/value pairs to summarize an intelligence report."
```

It should have an `intelligence` component (this is why it's currently failing). Did you upgrade the docker container or did you install it from scratch?

**Comment by tomchop** [comment] 2021-11-16 07:37
I confirm that I can't reproduce this on a fresh container pull / install. @jaegeral were you able to? I think the file not being up-to-date is the problem here. Waiting for @cudeso to confirm whether this is the case, otherwise I'll close this in a few days.

**Comment by jaegeral** [comment] 2021-11-16 09:13
No can't repro either. I wonder if we could improve the error handling in https://github.com/google/timesketch/blob/b027bf370bb964a5ae039c0a80429cf54ec28862/timesketch/lib/ontology.py#L61 if the value is not present in the config file.

And also pass the Value Error as something that the user can see and not `internal server error` WDYT?

**Comment by cudeso** [comment] 2021-11-16 09:32
> Thanks for filing @cudeso! Can you tell us a bit more about what your setup looks like?

I installed it from scratch, with the steps outlined in the [install guide](https://github.com/google/timesketch/blob/master/docs/guides/admin/install.md)

Actually, the ontology file wasn't there
```
docker exec -it timesketch_timesketch-worker_1 sh -c '/bin/ls /etc/timesketch'
features.yaml	  sigma		     tags.yaml      generic.mappings  plaso.mappings  sigma_config.yaml  timesketch.conf
docker exec -it timesketch_timesketch-web_1 sh -c '/bin/ls /etc/timesketch'
features.yaml	 sigma		  tags.yaml      generic.mappings  plaso.mappings  sigma_config.yaml  timesketch.conf
```

I manually added the files to the containers (`docker cp ontology.yaml timesketch_timesketch-worker_1:/etc/timesketch/`) but no luck so far. The error message remains the same.

It's a test environment. I'll remove the containers and restart "deploy_timesketch.sh" and provide you feedback.

**Comment by cudeso** [comment] 2021-11-16 09:45
I don't know if it's necessary (can be referenced somewhere else) but I don't see the ontology.yaml file referenced in the [deployment script](https://github.com/google/timesketch/blob/master/contrib/deploy_timesketch.sh)

**Comment by jaegeral** [comment] 2021-11-16 09:45
Hm, what do you get with:
```
sudo docker ps
```

When your docker images where built?

**Comment by jaegeral** [comment] 2021-11-16 09:54
Ah ftr, I have not used the deploy script in ages, did you try to repro with the deploy script @tomchop  ?

**Comment by cudeso** [comment] 2021-11-16 10:09
I tried with 

```
diff deploy_timesketch.sh deploy_timesketch-new.sh
80a81
> curl -s $GITHUB_BASE_URL/data/ontology.yaml > timesketch/etc/timesketch/ontology.yaml
```

This **solved** the problem. 
I need to deploy it on a second instance and will check if it's indeed the cause. Maybe it's useful to add a "are-all-configs-there?"-check on the startup?

**Comment by cudeso** [comment] 2021-11-16 10:34
Seems to be solved. https://github.com/google/timesketch/pull/2032

**Comment by jaegeral** [comment] 2022-01-10 09:28
Ack will close the issue then, thx

**Closed by jaegeral** 2022-01-10 09:28 UTC
Labels: Bug, Needs triage
