### ISSUE TITLE
Bug: Chrome/FF-Uncaught TypeError: crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by jknyght9** [google/timesketch#2410] opened 2022-11-03 14:30 UTC
**Describe the bug**
After a clean installation of Timesketch on Fedora 36 server, I attempt to log in to the Timesketch UI using the account I set up in the installation. It successfully logs in; however, the UI does not come up. In the web developer tools console, I receive an error "Uncaught TypeError: crypto.randomUUID is not a function" in the SigmaRuleTemplates.js

**To Reproduce**
1. Install a clean version of Timesketch
2. Login 
3. Open developer tools and review console output

**Expected behavior**
The ability to interact with the web UI

**Desktop (please complete the following information):**
 - OS: Fedora Server 36
 - FF 106/Chrome 107/Safari 16

**Comment by jknyght9** [comment] 2022-11-03 15:24
Just installed under Ubuntu 22.04 LTS Server and have the same issue

**Comment by jknyght9** [comment] 2022-11-04 14:15
More console info

![Screen Shot 2022-11-04 at 9 14 03 AM](https://user-images.githubusercontent.com/5823202/199996622-bc2d35d0-c59f-48d2-9c72-18df1146ad09.png)

**Comment by FrankShorty** [comment] 2022-11-07 09:11
I have the same issue. Fresh install both locally (docker desktop) and on Ubuntu 22.04 TLS.

**Comment by jaegeral** [comment] 2022-11-09 08:12
Closing in favour of #2411 2363

**Comment by jaegeral** [comment] 2022-12-02 22:27
Ok that was closed by mistake. Sorry. It seems like the installed node version on the system is to old. Will check if I can reproduce this and how to improve documents to prevent this

**Comment by jaegeral** [comment] 2022-12-02 22:31
To check which Node version is installed on a Docker instance, follow these steps:

First, access the Docker container that is running the Node application by using the docker exec command. For example: docker exec -it my_node_container /bin/bash.

Once inside the container, run the `node -v` command to display the installed Node version. This will output the version number of Node, such as v14.9.0.

To exit the container, use the `exit` command.

Alternatively, you can use the docker inspect command to retrieve information about the Docker container, including the installed Node version. For example: `docker inspect my_node_container | grep "NodeVersion"`. This will output the Node version as part of the container's metadata.

By following these steps, you can easily check which Node version is installed on a Docker instance. This information is useful for ensuring that the application is using the desired Node version and for keeping track of any updates that may be needed.

**Comment by jnimmo** [comment] 2022-12-08 01:48
Node isn't installed on the timesketch_web Docker images, it's just being served up with Flask

**Comment by psrok1** [comment] 2022-12-09 17:00
I have the same problem. And just like @jnimmo pointed out, the problem is not server-side but client-side. Web part uses `crypto.randomUUID` from Web Crypto API which is available only in secure context (HTTPS)

- https://github.com/google/timesketch/blob/016d2b0b19a51994de42fd2d7ae1c3f82b5066cf/timesketch/frontend/src/utils/SigmaRuleTemplates.js#L19
- https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

So if you frontend uses Crypto API: TLS in not optional but mandatory.

**Comment by jaegeral** [comment] 2022-12-09 17:34
Thx I will review it next week and most likely fix it.

**Comment by jaegeral** [comment] 2022-12-12 12:56
Please let me know if you still run into the issue.

**Closed** 2022-12-12 12:55 UTC
Labels: Bug

**Comment by jan-tee** [comment] 2023-01-01 15:17
Issue still exists when installing latest using deploy_timesketch.sh script and not using TLS.

**Comment by jnimmo** [comment] 2023-01-25 20:20
Yeah pulling the Docker image built 7 days ago and have the same issue. Where is the 'latest' Docker tag built from? Would be great to get some visibility of the Docker build process

**Comment by kudrew** [comment] 2023-01-26 21:55
v1 ui breaks because of the crypto.randomUUID issue. 

A dirty way to get the project running the v2 ui by editing the nginx.conf file and set `proxy_pass` to `http://timesketch-web-v2:5000/` regardless of location `/` or `/v2`  like so:

```
events {
    worker_connections 768;
}

http {
    server {
        listen 80;
        listen [::]:80;
        client_max_body_size 0m;
        location / {
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            proxy_pass http://timesketch-web-v2:5000/;
            proxy_read_timeout 120s;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /v2/ {
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            proxy_pass http://timesketch-web-v2:5000/;
            proxy_read_timeout 120s;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
```

**Comment by Drookoo** [comment] 2023-01-26 22:01
v1 ui breaks because of the crypto.randomUUID issue. 

A dirty way to get the project running the v2 ui by editing the nginx.conf file and set `proxy_pass` to `http://timesketch-web-v2:5000/` regardless of location `/` or `/v2`  like so:

```
events {
    worker_connections 768;
}

http {
    server {
        listen 80;
        listen [::]:80;
        client_max_body_size 0m;
        location / {
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            proxy_pass http://timesketch-web-v2:5000/;
            proxy_read_timeout 120s;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /v2/ {
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            proxy_pass http://timesketch-web-v2:5000/;
            proxy_read_timeout 120s;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
```
