### ISSUE TITLE
Safari displays "invalid date" for timelines and views

### ISSUE THREAD

**Issue by pettai** [google/timesketch#427] opened 2017-09-12 19:02 UTC
Latest stable timesketch release (20170721) displays "invalid date" in the GUI

![invalid-date](https://user-images.githubusercontent.com/3317462/30343329-773cb572-97fd-11e7-82be-1a230579f7c6.png)

**Comment by pettai** [comment] 2017-09-13 10:30
(timesketch 2016.11 was the last pypi version that displays the date / time correctly)

**Comment by berggren** [comment] 2017-09-15 14:34
Huh, I believe that this has been fixed, but should have been fixed in the last release. Let me do some testing on my side.

What SQL backend are you using?

**Comment by pettai** [comment] 2017-09-15 17:37
from /etc/timesketch.conf:
SQLALCHEMY_DATABASE_URI = 'postgresql://timesketch:XXXXXX@localhost/timesketch'

# dpkg -l | grep postgres
ii  postgresql                         9.5+173                                    all          object-relational SQL database (supported version)
ii  postgresql-9.5                     9.5.8-0ubuntu0.16.04.1                     amd64        object-relational SQL database, version 9.5 server
ii  postgresql-client-9.5              9.5.8-0ubuntu0.16.04.1                     amd64        front-end programs for PostgreSQL 9.5

**Comment by pettai** [comment] 2017-10-08 07:55
I noticed that the vagrant snapshot is affected too

**Comment by berggren** [comment] 2019-01-14 12:01
I can't reproduce this using Safari 12.0.2. The dates show just fine. Closing this out but feel free to open again if you still see problems @pettai

**Closed by berggren** 2019-01-14 12:01 UTC
Labels: Bug, Support
