### ISSUE TITLE
Vagrant Does not have tsctl installed

### ISSUE THREAD

**Issue by nm8800** [google/timesketch#547] opened 2018-03-01 02:43 UTC
Attempted to run timesketch through the vagrant method detailed in the docs. I noticed that timesketch wasn't installed, as I attempted to run the tsctl command. Once I installed the program, it seems that one would have to continue with a manual installation.  Still haven't gotten it to work yet, just wanted to share this.

**Comment by adamjnichols** [comment] 2018-03-01 03:08
Hi there; I'm not able to reproduce with a current clone of master.  Could you tee the output of `vagrant up` to a file and upload as a gist so we can see what might have gone wrong?

**Comment by nm8800** [comment] 2018-03-01 03:55
Here's my output from vagrant up

[vangrant_up_output.txt](https://github.com/google/timesketch/files/1769731/vangrant_up_output.txt)

**Comment by adamjnichols** [comment] 2018-03-01 04:32
There are some errors related to attempts to symlink at the bottom there.  May I have your platform details please?  Can you also try `vagrant up --no-bin-links`?

**Comment by nm8800** [comment] 2018-03-01 04:34
Thank you for the prompt reply. I'm attempting to run this on a Win7 Professional 64-bit. I'll try that command and forward the output.

**Comment by nm8800** [comment] 2018-03-01 04:38
Don't have the --no-bin-links option available... Probably because I'm running Vagrant on Windows

**Comment by adamjnichols** [comment] 2018-03-01 04:39
Poking around here, it seems that won't be of much use.  I suspect you might have problems due to the length of that path on Windows.  Let me try a few things and update this issue with what I find.

**Comment by nm8800** [comment] 2018-03-01 04:43
Thank you @adamjnichols

**Comment by adamjnichols** [comment] 2018-03-01 17:40
Sorry to report this appears to be a bug with Yarn within Vagrant:

https://github.com/yarnpkg/yarn/issues/4908

I would suggest adding your issue/following that bug for a fix.  Sorry about that. :(

**Comment by adamjnichols** [comment] 2018-03-01 18:03
Could you try to clone the branch vagrant-link-issue and run `vagrant up` to see if you still run into the issue?

**Comment by adamjnichols** [comment] 2018-03-06 02:09
Hi there -- were you able to try this?

**Comment by nm8800** [comment] 2018-03-06 17:27
Hello, so I tested the clone you recommended. I now have a login page for Timesketch, however the default credentials will not work (spock/spock also tried timesketch/timesketch). I've included the output from the installation. I believe the problem continues to be with yarn. 

[output.txt](https://github.com/google/timesketch/files/1785986/output.txt)

**Comment by adamjnichols** [comment] 2018-03-07 15:53
Okay!  So, i have some bad news.  It seems that this is an open [issue](https://github.com/yarnpkg/yarn/issues/4782) with yarn.  I'll try to explain.

- There is a requirement for running Vagrant/Docker/etc. on Windows with yarn or other js package frameworks that `--no-bin-links` or equivalent is passed to the package manager when installing.  This is maybe due to the complications of a shared virtual folder and the Windows MAX_PATH length limit of 260 characters.

- Yarn/nodejs require a shortcut directory within `node_modules` labeled `.bin.` that contains the symlinks to all of the binaries used to run/test/install or otherwise build application js files and dependencies.  It's perhaps unsurprising that `--no-bin-links` fails to link in `.bin` but here we are.

- There exists some other additional behavior that is introduced by `--no-bin-links` that appears to be overridden by `--check-files`.  I don't completely understand exactly what is happening here, but as we can't use `--no-bin-links` at this time, it doesn't seem to matter. 

- At this point, it's up to the yarn project to address this issue either through another feature that more creatively addresses the MAX_PATH limitation or provides a different way forward.

You should know that this topic has been discussed quite a lot across many projects, and there are a great deal of workarounds that exist for this issue.  However, all of them that I'm aware of fundamentally break the idea of a Vagrant install by forcing you to institute some hacky manual things to get them to work.

If I have time, I'll explore some more creative ways we might overcome this.

**Comment by nm8800** [comment] 2018-03-09 00:08
Well I can always use the Ubuntu VM instead of Vagrant. I don't mind using Vagrant on Linux as well. I'm glad that we were able to bring this issue to light in case someone else runs into the same problem.

**Comment by berggren** [comment] 2018-03-20 07:52
Closing this issue as we have no control over this. I updated our Vagrant documentation advising to use Linux or MacOS instead (as the host)

**Closed by berggren** 2018-03-20 07:52 UTC
