### ISSUE TITLE
[Installation failure] Timesketch installation failing, URL doesn't exist

### ISSUE THREAD

**Issue by SkyBlue-B** [google/timesketch#1875] opened 2021-07-15 11:22 UTC
deploy_timesketch.sh: 19: [: Illegal number: 
/usr/bin/docker-compose
* Setting vm.max_map_count for Elasticsearch
* Setting default config parameters..OK
* Setting Elasticsearch memory allocation to 4GB
* Fetching configuration files..deploy_timesketch.sh: 80: cannot create timesketch/etc/timesketch/timesketch.conf: Directory nonexistent

Is the URL still accessible? https://raw.githubusercontent.com/google/timesketch/master

**Comment by jaegeral** [comment] 2021-07-15 15:48
Hm not familiar with the shell script as this was contributed, @lprat  can you help here?

**Comment by lprat** [comment] 2021-07-15 16:54
Hi,

@SkyBlue-B can you give more detail, please run script "https://raw.githubusercontent.com/google/timesketch/master/contrib/deploy_timesketch.sh" with "bash -x deploy_timesketch.sh >log 2>&1" and past log.

(did you follow the instructions: https://timesketch.org/getting-started/install.html ? )

**Comment by jaegeral** [comment] 2021-08-16 19:54
@SkyBlue-B did the comment from lprat help your issue? If not please update the issue or we would close in 4 weeks.

Thx a lot

**Comment by berggren** [comment] 2021-09-12 22:14
Closing this out is lack of update. The script is working as intended in the last deployment tests.

**Closed by berggren** 2021-09-12 22:14 UTC
Labels: Support, Deployment
