### ISSUE TITLE
Plaso Upload Issues

### ISSUE THREAD

**Issue by landw1re** [google/timesketch#156] opened 2015-12-08 15:01 UTC
I've just installed all the dependencies and Timesketch on a Ubuntu 14.04LTS box. Everything built OK without issue and Redis, Elasticsearch, Celery & Timesketch start-up fine. The issue that I'm having is with the Uploading of Plaso files. I tried it with a small (639K) .plaso file to test things out. I created the small file from a larger (4GB) plaso file by using the following psort.py command:

```python
psort.py -q -o pstorage -w testing.plaso --slice "2015-01-08 09:47:16" --slice_size 100 timeline.plaso
```
**Note**: the psort.py command runs clean and I don't receive any errors. The file doesn't appear to be corrupted. I changed the output to l2tcsv just to make sure there was data and it produced a 6.0M csv with content.

When I upload the small file I keep getting the following errors:
### Error from tsctl runserver
```python
[2015-12-08 14:37:09,173: INFO/MainProcess] Received task: timesketch.lib.tasks.run_plaso[e604c57e4f8440ac8c05f103a606f242]
127.0.0.1 - - [08/Dec/2015 14:37:09] "POST /api/v1/upload/ HTTP/1.1" 201 -
[2015-12-08 14:37:09,223: INFO/Worker-8] Index: e604c57e4f8440ac8c05f103a606f242
[2015-12-08 14:37:09,224: INFO/Worker-8] Timeline name: testing
[2015-12-08 14:37:09,236: INFO/Worker-8] Starting new HTTP connection (1): 127.0.0.1
[2015-12-08 14:37:09,273: ERROR/MainProcess] Task timesketch.lib.tasks.run_plaso[e604c57e4f8440ac8c05f103a606f242] raised unexpected: RequestError(400, u'mapper_parsing_exception', {u'status': 400, u'error': {u'type': u'mapper_parsing_exception', u'root_cause': [{u'reason': u'Mapping definition for [_timestamp] has unsupported parameters:  [path : datetime]', u'type': u'mapper_parsing_exception'}], u'caused_by': {u'reason': u'Mapping definition for [_timestamp] has unsupported parameters:  [path : datetime]', u'type': u'mapper_parsing_exception'}, u'reason': u'Failed to parse mapping [plaso_event]: Mapping definition for [_timestamp] has unsupported parameters:  [path : datetime]'}})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/__init__.py", line 162, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/tasks.py", line 79, in run_plaso
    output_module, storage_file, plugins, queue_producers)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 417, in ProcessStorage
    output_module, deduplicate_events)
  File "/usr/lib/python2.7/dist-packages/plaso/output/interface.py", line 167, in __init__
    self._output_module.WriteHeader()
  File "/usr/lib/python2.7/dist-packages/plaso/output/timesketch_out.py", line 213, in WriteHeader
    index=self._index_name, body={u'mappings': _document_mapping})
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 105, in create
    params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception')
```
### Error produced by Elasticsearch
```java
[2015-12-08 14:37:09,267][DEBUG][action.admin.indices.create] [Guido Carosella] [e604c57e4f8440ac8c05f103a606f242] failed to create
MapperParsingException[Failed to parse mapping [plaso_event]: Mapping definition for [_timestamp] has unsupported parameters:  [path : datetime]]; nested: MapperParsingException[Mapping definition for [_timestamp] has unsupported parameters:  [path : datetime]];
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:381)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: MapperParsingException[Mapping definition for [_timestamp] has unsupported parameters:  [path : datetime]]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:266)
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:260)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:243)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:191)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:387)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:261)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:378)
        ... 6 more
[2015-12-08 14:37:09,268][INFO ][rest.suppressed          ] /e604c57e4f8440ac8c05f103a606f242 Params: {index=e604c57e4f8440ac8c05f103a606f242}
MapperParsingException[Failed to parse mapping [plaso_event]: Mapping definition for [_timestamp] has unsupported parameters:  [path : datetime]]; nested: MapperParsingException[Mapping definition for [_timestamp] has unsupported parameters:  [path : datetime]];
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:381)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: MapperParsingException[Mapping definition for [_timestamp] has unsupported parameters:  [path : datetime]]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:266)
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:260)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:243)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:191)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:387)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:261)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:378)
        ... 6 more
```

**Comment by berggren** [comment] 2015-12-11 11:57
Hi Steven,

Couple of questions:
* What version of Plaso are you using?
* Have you tried: psort.py -o timesketch testing.plaso ?

This looks like ES don't get the right mapping. I will try to reproduce.

/jbn

**Comment by landw1re** [comment] 2015-12-12 18:29
Hey Johan,

I'm running the latest plaso 1.3.0 version. I'm running the stable branch so I don't currently have access to the -o timesketch switch.

I used the following to bootstrap a very bare-bones Ubuntu Image made from debootstrap running with Docker:
```bash
cd /tmp
apt-get update && apt-get dist-upgrade && apt-get install -y software-properties-common wget
add-apt-repository -y universe
add-apt-repository -y ppa:webupd8team/java
add-apt-repository -y ppa:chris-lea/redis-server
add-apt-repository -y ppa:gift/stable
wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.1.0/elasticsearch-2.1.0.deb
apt-get update

echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

apt-get install -y oracle-java8-installer
update-java-alternatives -s java-8-oracle
apt-get install -y oracle-java8-set-default
apt-get install -y python2.7 python-dev nano build-essential libffi-dev sqlite3 libsqlite3-dev python-plaso redis-server

dpkg -i elasticsearch-2.1.0.deb
mkdir -p /root/timesketch
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py

echo "script.groovy.sandbox.enabled: true" >> /etc/elasticsearch/elasticsearch.yml
echo "network.host: 127.0.0.1" >> /etc/elasticsearch/elasticsearch.yml
echo "http.port: 9200" >> /etc/elasticsearch/elasticsearch.yml

pip install timesketch
cp /usr/local/share/timesketch/timesketch.conf /etc/.

# only used for local testing
export C_FORCE_ROOT="true"

service elasticsearch start
service redis-server start
celery -A timesketch.lib.tasks worker --loglevel=info &
tsctl add_user -u testuser
tsctl runserver &
```

**Comment by berggren** [comment] 2015-12-14 13:21
Hi,

I see the problem now. You are running the new Elasticsearch 2.x version.
Timesketch is not yet compatible with this version due to breaking changed
in the way Elastic does mappings. This will be fixed for the next release,
but until then please tun the latest stable release of the 1.x series.

I will make sure this is pointed out in the documentation. Thanks for
reporting this!
/jbn

**Comment by marcurdy** [comment] 2016-02-15 04:00
@berggren Does the latest psort.py support elastic output to ES 2.2?  I'm getting the mapper_parsing_exception.  thanks.

**Comment by berggren** [comment] 2016-02-15 14:58
@marcurdy No, unfortunately not, the fix is not yet in. I'm still working on it. To track progress, see #166

**Closed** 2016-04-08 08:04 UTC
Labels: bug, wontfix

**Comment by enhanced** [comment] 2016-04-23 15:48
Looks like ES and Timesketch mapping is still broken in 1.4 and 1.4.1

```elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception', u'Mapping definition for [_timestamp] has unsupported parameters:  [path : datetime]')```

**Comment by berggren** [comment] 2016-04-26 11:25
Hi,

Yes the fix is not yet pushed yet (any time now :). It will be part of the
1.5 Plaso release.
https://github.com/log2timeline/plaso/issues/607

Kind regards,
Johan
