### ISSUE TITLE
Unable to import plaso data into Timesketch

### ISSUE THREAD

**Issue by CdtDelta** [google/timesketch#870] opened 2019-04-20 18:06 UTC
This might be related to #836 

I'm running plaso from the docker hub image (plaso - log2timeline version 20190331), and timesketch from the docker instance in the repo (I'm pulling from source). I'm able to create an image with plaso, but not able to upload them into timesketch.

I'm running log2timeline with the following command:
docker run -ti --name=plaso --mount type=bind,source="$(pwd)"/<Case Folder>,target=/cases log2timeline/plaso log2timeline.py --status_view window --logfile /cases/Admin/Timeline/<computer-name>/<computer-name>.log /cases/Admin/Timeline/<computer-name>/<computer-name>.plaso /cases/Evidence/<computer-name>

The source data is triage files NOT a hard drive image. Plaso completes successfully but with some errors parsing data.

I'm running timesketch with the following command:
sudo docker-compose up
from the timesketch/docker directory

When I try to upload the plaso file to timesketch I get the following error:

 2019-04-20 15:21:18,123 [INFO] (MainProcess) PID:98 <data_location> Determined data location: /usr/share/plaso
2019-04-20 15:21:18,167 [INFO] (MainProcess) PID:98 <timesketch_out> Timeline name: <computer>
2019-04-20 15:21:18,167 [INFO] (MainProcess) PID:98 <timesketch_out> Owner of the timeline: None
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 68, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 54, in Main
    tool.ProcessStorage()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/psort_tool.py", line 492, in ProcessStorage
    self._CheckStorageFile(self._storage_file_path)
  File "/usr/lib/python2.7/dist-packages/plaso/cli/psort_tool.py", line 116, in _CheckStorageFile
    logger.warning('Appending to an already existing storage file.')
  File "/usr/lib/python2.7/logging/__init__.py", line 1186, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 766, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 963, in emit
    self.stream = self._open()
  File "/usr/lib/python2.7/dist-packages/plaso/lib/loggers.py", line 40, in _open
    return gzip.open(self.baseFilename, self.mode)
  File "/usr/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 13] Permission denied: u'/psort-20190420T152118.log.gz'

When I convert the plaso file to a csv with the l2tcsv option and psort then try to upload it to timesketch I get the following error:

                      Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/tasks.py", line 417, in run_csv_jsonl
    for event in read_and_validate(source_file_path):
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/utils.py", line 71, in read_and_validate_csv
    'Missing fields in CSV header: {0:s}'.format(missing_fields))
RuntimeError: Missing fields in CSV header: [u'message', u'datetime', u'timestamp_desc']

CSV file headers
date,time,timezone,MACB,source,sourcetype,type,user,host,short,desc,version,filename,inode,notes,format,extra

So obviously the headers are missing...I can't share any other data because it's not sanitized. However the output files from psort (any output format) is 2 GB or larger (depending on the output format I choose).

I'm not entirely sure if this is an error on the plaso side or the timesketch side.

**Comment by berggren** [comment] 2019-04-23 17:42
Hi, it looks like you are uploading a gzipped file?
```
IOError: [Errno 13] Permission denied: u'/psort-20190420T152118.log.gz'
```

You should upload the .plaso file that log2timeline.py produces.
Also set the upload dir to somewhere where the user who runs Timesketch can read. Default is /tmp/

l2tcsv format is not supported by default. You need to convert the message fields to:
```CSV header: [u'message', u'datetime', u'timestamp_desc']```
and any other field you want. But I recommend uploading the .plaso file instead.

**Comment by CdtDelta** [comment] 2019-04-23 19:18
> Hi, it looks like you are uploading a gzipped file?

Nope, it's a .plaso file from log2timeline

![timesketch-step-one](https://user-images.githubusercontent.com/130858/56609319-52649c00-65fc-11e9-8757-9f80a8e5bc9b.png)

> You should upload the .plaso file that log2timeline.py produces.
> Also set the upload dir to somewhere where the user who runs Timesketch can read. Default is /tmp/

How do I do that in the docker instance of timesketch?

**Comment by Onager** [comment] 2019-04-23 21:01
It looks like this is actually the log file from psort running in the
Timesketch container. The latest version of Plaso enables the log file by
default, and it tries to create a log file in the same directory as the
source file if I recall correctly. Setting a log file somewhere else (/tmp)
when Timesketch runs psort should resolve this.

**Comment by michaelschratt** [comment] 2019-04-24 08:46
In this case, psort tries to write the gzipped log file to the / directory, where user nobody (celery runs under nobody) has no write rights.

**Comment by CdtDelta** [comment] 2019-04-24 13:16
So how do I configure it to write to the correct location?

**Comment by CdtDelta** [comment] 2019-04-26 20:52
Just wanted to bump this, is there something I can configure in the docker-compose.yml file or somewhere else to get this working correctly?

**Comment by joachimmetz** [comment] 2019-04-27 06:44
you can set the location of the log file with `--logile`, should work for both log2timeline.py and posrt.py. So where psort is invoked add log file and point it to a location where the process has write access

**Comment by CdtDelta** [comment] 2019-05-08 19:23
I ran a git pull today on my local timesketch and tried running docker-compose again from the docker sub-directory. The import Timelines screen is now showing:

Supported Plaso version: 20190429

I tried uploading one of the plaso files from before, and now I'm getting a new error:

                        ERROR: Unsupported output format: timesketch.

usage: psort.py [-h] [--troubles] [-V] [--analysis PLUGIN_LIST]
                [--process_memory_limit SIZE]
                [--temporary_directory DIRECTORY] [--disable_zeromq]
                [--worker-memory-limit SIZE] [--logfile FILENAME] [-d] [-q]
                [--status_view TYPE] [--slice DATE] [--slice_size SLICE_SIZE]
                [--slicer] [--data PATH] [-a] [--language LANGUAGE]
                [-z TIMEZONE] [-o FORMAT] [-w OUTPUT_FILE]
                [--name TIMELINE_NAME] [--index INDEX]
                [--flush_interval FLUSH_INTERVAL] [--doc_type DOCUMENT_TYPE]
                [--username USERNAME] [--profilers PROFILERS_LIST]
                [--profiling_directory DIRECTORY]
                [--profiling_sample_rate SAMPLE_RATE]
                [STORAGE_FILE] [FILTER]

Again I'm uploading a plaso file that was created with plaso - log2timeline version 20190331 in my original post.
I tried the CSV file from psort on the same plaso file but it's still complaining about the field names.

**Comment by joachimmetz** [comment] 2019-05-08 19:33
@CdtDelta which version of python is using psort and which version did you install timesketch under?

**Comment by CdtDelta** [comment] 2019-05-08 19:36
This is all through docker containers, so it's whatever is set up in the timesketch/docker environment, and whatever is on docker hub for plaso.

**Comment by joachimmetz** [comment] 2019-05-08 19:39
based on https://hub.docker.com/r/log2timeline/plaso/dockerfile

this looks like Python 3 plaso, where is the timesketch dockerfile? or how did you install timesketch?

**Comment by CdtDelta** [comment] 2019-05-08 19:43
I did a git clone of the timesketch repo, I go to the docker sub-directory, and per the docs:

https://github.com/google/timesketch/tree/master/docker

I run sudo docker-compose up to start it up.

**Comment by joachimmetz** [comment] 2019-05-08 19:47
in https://github.com/google/timesketch/blob/master/docker/Dockerfile#L30 change pip to pip3 

There is WIP to not use 2 package managers https://github.com/google/timesketch/issues/883

@berggren could you update the dockerfile to use pip3?

**Comment by CdtDelta** [comment] 2019-05-08 19:50
wouldn't line 8 need to be changed to python3-pip then?

**Comment by joachimmetz** [comment] 2019-05-08 20:00
Yeah, I was being terse (due to multi tasking):
```
                       python-dev\
                       python-pip\
                       python-psycopg2
```
also need to be:
```
                       python3-dev\
                       python3-pip\
                       python3-psycopg2
```

and remove `python-plaso`

**Comment by CdtDelta** [comment] 2019-05-08 20:02
No worries just wanting to confirm that.....

So I'm clear get rid of python-plaso completely not change it to python3-plaso (if it exists) correct?

**Comment by joachimmetz** [comment] 2019-05-08 20:04
Try https://github.com/google/timesketch/pull/887, let us know if that fixes the issue, so @berggren can merge the changes when time permits.

**Comment by joachimmetz** [comment] 2019-05-08 20:05
> So I'm clear get rid of python-plaso completely not change it to python3-plaso (if it exists) correct?

Correct plaso-tools depends on python3-plaso so apt takes care of that

**Comment by CdtDelta** [comment] 2019-05-08 20:30
Ok now I'm back to the original issue with the plaso files (I put in the <TIMELINE> part):

                        2019-05-08 20:28:34,317 [INFO] (MainProcess) PID:95 <data_location> Determined data location: /usr/share/plaso
2019-05-08 20:28:34,374 [INFO] (MainProcess) PID:95 <timesketch_out> Timeline name: <TIMELINE>
2019-05-08 20:28:34,374 [INFO] (MainProcess) PID:95 <timesketch_out> Owner of the timeline: None
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 68, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 54, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 492, in ProcessStorage
    self._CheckStorageFile(self._storage_file_path)
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 116, in _CheckStorageFile
    logger.warning('Appending to an already existing storage file.')
  File "/usr/lib/python3.6/logging/__init__.py", line 1320, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1071, in emit
    self.stream = self._open()
  File "/usr/lib/python3/dist-packages/plaso/lib/loggers.py", line 38, in _open
    self.baseFilename, mode=self.mode, encoding=self.encoding)
  File "/usr/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/psort-20190508T202834.log.gz'

**Comment by joachimmetz** [comment] 2019-05-09 04:47
@CdtDelta did you try setting `--logfile` to a different location?

**Comment by CdtDelta** [comment] 2019-05-09 13:08
No because I don't know how to do that in the docker version of timesketch.

**Comment by joachimmetz** [comment] 2019-05-09 13:16
One option is to run psort with timesketch output module inside the timesketch docker container.

Another thing I would try is (in the source in the docker container) add `--logfile` to:
https://github.com/google/timesketch/blob/2bdaedf3b1533083e7afa10457afd9357f80bc34/timesketch/lib/tasks.py#L361

@berggren do you know which path in the container would be suitable to store temporary logs? or should we add a `--nolog` option? or make this part of `-q`?

**Comment by CdtDelta** [comment] 2019-05-23 15:24
> One option is to run psort with timesketch output module inside the timesketch docker container.

Do you mean create the plaso file, then copy that into the timesketch docker instance, and run psort with the timesketch output?

Or were all the comments for @berggren ? :)

I'm just asking if there's something we're waiting for me to do vs someone else doing....

**Comment by joachimmetz** [comment] 2019-05-23 17:57
> Do you mean create the plaso file, then copy that into the timesketch docker instance, and run psort with the timesketch output?

@CdtDelta nope this response was for you. That is what I mean indeed.

> Or were all the comments for @berggren ? :)

Somewhat, but I know he's preoccupied with many things.

**Comment by ZeArioch** [comment] 2019-05-28 12:19
Hi! I ran into the same situation. Editing `/usr/local/lib/python3.6/dist-packages/timesketch/lib/tasks.py` directly in the Docker container to add `'--logfile', '/tmp/psort.log'` to the `cmd` array as suggested by @joachimmetz worked for me. I just had to restart the container after the edit.

**Comment by chapinb** [comment] 2019-09-10 16:22
Still an issue as of 2362549 when using `docker-compose up`. Was resolved using @ZeArioch's method above. 

Separately I also needed to modify paths away from `/var/lib` to get the stack functioning on macOS.

**Comment by einfallstoll** [comment] 2019-12-05 11:19
Because I was not happy with the situation I patched it in a custom image. I was facing some problems here: The `setup.sh` script had to ran *after* the timesketch server was configured, but *before* the timesketch server will be started. So I had to patch the file `docker-entrypoint.sh` to get my script running.

### Dockerfile
```
FROM timesketch

# Copy the setup script into the container
COPY setup.sh /
RUN chmod a+x /setup.sh

# Expose the port used by Timesketch
EXPOSE 5000

# Load the entrypoint script to be run later
ENTRYPOINT ["/setup.sh"]

# Invoke the entrypoint script
CMD ["timesketch"]
```

### setup.sh
```
#!/bin/bash

# Manipulate the original entrypoint script to prevent it from starting the timesketch server
sed -Ei 'N;s#exec ([`"]).+\1##' /docker-entrypoint.sh

# Run original entrypoint script to run setup tasks
bash -c "/docker-entrypoint.sh timesketch"

# Patch command
sed -i "/status_view/s/$/, '--logfile', '\/tmp\/psort.log'/" /usr/local/lib/python3.6/dist-packages/timesketch/lib/tasks.py

# Start timesketch server
exec `bash -c "/usr/local/bin/celery -A timesketch.lib.tasks worker --uid nobody --loglevel info &\
    gunicorn -b 0.0.0.0:80 --access-logfile - --error-logfile - --log-level info --timeout 120 timesketch.wsgi:application"`
```

**Comment by deralexxx** [comment] 2019-12-14 15:03
Is there a way to also fix it for web uploads from plaso files? I did pull the latest timesketch github repo and did:

`sudo docker-compose up`

And uploading the plaso file: https://github.com/log2timeline/plaso/blob/master/test_data/pinfo_test.plaso

Via web upload gave me:

`imesketch_1     | [2019-12-14 14:52:55,935: INFO/ForkPoolWorker-1] Task timesketch.lib.tasks.run_plaso[9f71f2a4-87d5-4436-8c79-dafb2b1dd248] succeeded in 9.44906489999994s: '2019-12-14 14:52:54,363 [INFO] (MainProcess) PID:42 <data_location> Determined data location: /usr/share/plaso
timesketch_1     | 2019-12-14 14:52:54,680 [INFO] (MainProcess) PID:42 <timesketch_out> Timeline name: pinfo_test
timesketch_1     | 2019-12-14 14:52:54,686 [INFO] (MainProcess) PID:42 <timesketch_out> Owner of the timeline: None
timesketch_1     | Traceback (most recent call last):
timesketch_1     |   File "/usr/bin/psort.py", line 85, in <module>
timesketch_1     |     if not Main():
timesketch_1     |   File "/usr/bin/psort.py", line 67, in Main
timesketch_1     |     tool.ProcessStorage()
timesketch_1     |   File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 501, in ProcessStorage
timesketch_1     |     self._CheckStorageFile(self._storage_file_path)
timesketch_1     |   File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 115, in _CheckStorageFile
timesketch_1     |     logger.warning('Appending to an already existing storage file.')
timesketch_1     |   File "/usr/lib/python3.6/logging/__init__.py", line 1320, in warning
timesketch_1     |     self._log(WARNING, msg, args, **kwargs)
timesketch_1     |   File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
timesketch_1     |     self.handle(record)
timesketch_1     |   File...'
docker_elasticsearch_1 exited with code 137

`

**Comment by einfallstoll** [comment] 2019-12-14 15:07
@deralexxx I'm working on this right now. Apparently the status array is empty and it tries to remove the first element (which does not exist). This causes the error.

However, I can only reproduce the issue by manually running `psort.py` twice using the same index specifier. If I randomize it, it works just fine. But to be honest, I'm not sure whether this is an issue of Plaso or Timesketch.

Maybe Plaso can't handle it, if Timesketch already created the index before...?

**Comment by deralexxx** [comment] 2019-12-14 15:32
Hm strange, I do run the docker locally on my machine so I do not pass any index specifiers to it.

Let me know if I should run any tests or get more data.

**Comment by jorlamd** [comment] 2020-01-01 17:49
Here is my full error trace. This is quite likely the untruncated version of the same issue. I have attempted solution mentioned in #1067 and it works.

`                        
2020-01-01 17:27:51,359 [INFO] (MainProcess) PID:247 <data_location> Determined data location: /usr/share/plaso
2020-01-01 17:27:51,530 [INFO] (MainProcess) PID:247 <timesketch_out> Timeline name: w10std
2020-01-01 17:27:51,530 [INFO] (MainProcess) PID:247 <timesketch_out> Owner of the timeline: None
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 85, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 67, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 501, in ProcessStorage
    self._CheckStorageFile(self._storage_file_path)
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 115, in _CheckStorageFile
    logger.warning('Appending to an already existing storage file.')
  File "/usr/lib/python3.6/logging/__init__.py", line 1320, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1071, in emit
    self.stream = self._open()
  File "/usr/lib/python3/dist-packages/plaso/lib/loggers.py", line 38, in _open
    self.baseFilename, mode=self.mode, encoding=self.encoding)
  File "/usr/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/psort-20200101T172751.log.gz'
`

**Comment by berggren** [comment] 2020-01-03 10:19
Sorry for the delay. This is indeed because of permission issues with celery. The non-development docker is in desperate need of a rewrite. I'll merge this fix proposed in #1067  and will start working on a more robust solution next week.

Thanks for fixing!

**Comment by berggren** [comment] 2020-01-03 10:20
Let me know if there are still issues with this.

**Comment by einfallstoll** [comment] 2020-01-13 13:42
@berggren 267744b works for me

**Comment by kiddinn** [comment] 2020-06-23 10:43
is this still an issue?

you can also upload the plaso file using the importer

```
pip install timesketch-import-client
timesketch_importer.py --sketch_id <ID> <FILE>
```

**Comment by berggren** [comment] 2020-06-26 11:53
Closing this as it has been resolved. docker support has been updated and refactored as well.

**Closed by berggren** 2020-06-26 11:53 UTC
Labels: Support
