### ISSUE TITLE
Support: Connection reset by peer error

### ISSUE THREAD

**Issue by NofLevi10root** [google/timesketch#3221] opened 2024-11-04 13:44 UTC
Version: The newest one [Had it in the previous version I taught maybe update will fix it but it didnt].
Description: Every time I'm trying to get list of timelines [sketch.list_timelines()] I get an error. I'm using many different functions from the API as "get_sketch", "list_sketches", and "upload" during the run so its cant be network problem
Error: 'Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')

Python code reference:
```
def get_timeline_id(api, sketch_id, timeline_name, logger):
    try:
        # Get the sketch
        logger.info(f"Fetching sketch with ID: {sketch_id}")
        sketch = api.get_sketch(sketch_id)
        if not sketch:
            logger.error(f"Sketch with ID {sketch_id} not found.")
            return None

        # Get the list of timelines for the given sketch
        logger.info(f"Getting list of timelines for sketch ID: {sketch_id}")
        timelines = sketch.list_timelines()
        logger.info("Pre timelines loop!")
        for timeline in timelines:
            logger.info("Timeline loop:" + str(timeline.id))
            if timeline.name == timeline_name:
                logger.info(f"Found timeline '{timeline_name}' with ID: {timeline.id}")
                return timeline.id

        logger.warning(f"Timeline '{timeline_name}' not found in sketch ID: {sketch_id}")
        return None

    except AttributeError as e:
        logger.error(f"API method error: {str(e)}")
        return None
    except Exception as e:
        logger.error(f"Unexpected error: {str(e)}")
        return None
```

**Comment by jkppr** [comment] 2024-11-04 14:17
Hi @NofLevi10root 
Thanks for raising this topic. Can you share some detailed steps on how to reproduce?

Running the following steps does work for me:
```
from timesketch_api_client import config
ts_client = config.get_client()
sketch = ts_client.get_sketch(1)
sketch.list_timelines()
[<timesketch_api_client.timeline.Timeline object at 0x7f9d95ccd9d0>, <timesketch_api_client.timeline.Timeline object at 0x7f9d95ccc550>]
```

**Comment by NofLevi10root** [comment] 2024-11-04 14:33
Its basically the same code wise.
Before that I'm creating the timeline give it around 1 minute sleep time [So its will be there for sure] and then I want to get the timeline ID [to use it later on] but when I try to get the list of timelines its telling me the connection error.
I also tried to close the connection and recreate it just before getting the timelines but its also doesn't work.

**Comment by jkppr** [comment] 2024-11-04 15:08
Do you mind sharing the full python error traceback when this happens in your script?

**Comment by NofLevi10root** [comment] 2024-11-04 15:21
Sure.
2024-11-04 15:13:14,201 - ERROR - Unexpected error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-11-04 15:13:14,261 - ERROR - Traceback (most recent call last):
  File "/home/random/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/random/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/random/.local/lib/python3.10/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/random/.local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/random/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/home/random/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/random/.local/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/random/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/random/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/random/.local/lib/python3.10/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/random/software/folder/modules/Velociraptor/AddToTimeSketch.py", line 226, in get_timeline_id
    timelines = sketch.list_timelines()
  File "/home/random/.local/lib/python3.10/site-packages/timesketch_api_client/sketch.py", line 942, in list_timelines
    data = self.lazyload_data()
  File "/home/random/.local/lib/python3.10/site-packages/timesketch_api_client/resource.py", line 42, in lazyload_data
    self.resource_data = self.api.fetch_resource_data(self.resource_uri)
  File "/home/random/.local/lib/python3.10/site-packages/timesketch_api_client/client.py", line 381, in fetch_resource_data
    response = self.session.get(resource_url, params=params)
  File "/home/random/.local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/random/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/random/.local/lib/python3.10/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
  File "/home/random/.local/lib/python3.10/site-packages/requests/sessions.py", line 724, in <listcomp>
    history = [resp for resp in gen]
  File "/home/random/.local/lib/python3.10/site-packages/requests/sessions.py", line 265, in resolve_redirects
    resp = self.send(
  File "/home/random/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/random/.local/lib/python3.10/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by jkppr** [comment] 2024-11-05 07:53
The traceback strongly suggests a network connection issue. You can check the following:

* Ensure you have a stable connection between all components of your Timesketch deployment (e.g. webserver & opensearch server). This depends on what deployment you are running.
* Increase the Opensearch Timeout in your config. Make sure to restart the deployment for changes to take effect.
* Test the commands mentioned [above](https://github.com/google/timesketch/issues/3221#issuecomment-2454837254) directly on the timesketch server.

**Comment by NofLevi10root** [comment] 2024-11-05 08:37
I tried increasing the opensearch timeout to 300. Still the same error.
I tried the minimal code for test. Still the same error.
I tried to remove the sketch and add new timelines remove some timelines [I taught maybe its bug or something].
And I'm pretty sure the connection is good since I manage to use all other API calls.
But I really don't know what to do anymore.

**Comment by jkppr** [comment] 2024-11-05 09:17
Please share a detailed overview of your setup and Timesketch deployment. Let's see if we can spot any other explanation on why this keeps happening to you.

**Comment by jkppr** [comment] 2024-11-05 13:40
* Are you using the [prod deployment](https://timesketch.org/guides/admin/install/) or a [dev deployment](https://timesketch.org/developers/getting-started/)?
* Did you try the example provided above without the nginx reverse proxy or behind it?
* What type of authentication are you using?

**Comment by jkppr** [comment] 2024-11-12 22:56
Sorry, but I can't reproduce your issue in my setups and can't help much more outside the above. Please check with your DevOps team if they can identify and fix the problem.

For now I'll close this support issue. Feel free to re-open this once it is confirmed as a bug and we have additional steps to reproduce it. Thanks.

**Closed by jkppr** 2024-11-12 22:56 UTC
Labels: Support
