### ISSUE TITLE
localhost:5000 Access to localhost was denied

### ISSUE THREAD

**Issue by bwhelan212** [google/timesketch#2936] opened 2023-10-11 02:27 UTC
I followed the getting started documentation and the commands in each step, but when i got to localhost:5000 I am receiving access denied.
<img width="1401" alt="Screen Shot 2023-10-10 at 7 20 59 PM" src="https://github.com/google/timesketch/assets/123424127/b89c2744-3ebb-431f-8c47-99a5a7a1d6b2">
Commands I ran:
```
1. docker compose up
2. ./tsdev.sh web
```

<img width="1156" alt="Screen Shot 2023-10-10 at 7 24 43 PM" src="https://github.com/google/timesketch/assets/123424127/9dd8f539-ab3a-4670-8ee2-c983479f23ec">
<img width="1027" alt="Screen Shot 2023-10-10 at 7 25 31 PM" src="https://github.com/google/timesketch/assets/123424127/6314c404-6e56-488e-b84b-8a808ad53b28">
<img width="1055" alt="Screen Shot 2023-10-10 at 7 26 29 PM" src="https://github.com/google/timesketch/assets/123424127/8685e174-f489-46a6-8015-067fd0e4e284">

**Comment by jkppr** [comment] 2023-11-03 10:08
Closing this since not being able to reproduce the problem and no reaction on questions. Feel free to re-open with more information.

**Closed by jkppr** 2023-11-03 10:08 UTC
Labels: Bug
