### ISSUE TITLE
Analyzer's saved views not showing up in summary

### ISSUE THREAD

**Issue by tomchop** [google/timesketch#3116] opened 2024-07-01 09:23 UTC
The yeti analyzer creates saved searches ([link](https://github.com/google/timesketch/blob/ec01d777bc5c013c1a67dfef27ae60f16870642a/timesketch/lib/analyzers/yetiindicators.py#L550)), but these do not get reported in the analyzer summary:

![image](https://github.com/google/timesketch/assets/1257972/ac12b8ba-e0ed-4e25-b788-4e1b7253242b)

The saved search gets created properly since it's accessible through the saved view menu, so I guess this is affecting the analyzer's reports only. I suspect this affects all analyzers that create saved views.

**Comment by jkppr** [comment] 2024-07-10 09:25
I cannot reproduce this issue. It just works for me:
![image](https://github.com/google/timesketch/assets/99879757/a6a40435-1c00-4565-a623-d91aa5173989)

based on offline discussions: Please reload the page and it should start showing. If you find a reliable way to reproduce the issue, please re-open.

Closing this issue as "not reproducible".

**Closed by jkppr** 2024-07-10 09:25 UTC
Labels: Bug, Analyzers
